# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: publish to npm

on:
  push:
    branches:
      - master
      - workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - run: npm i -g yarn
    - run: yarn config set "npmRegistries['https://registry.yarnpkg.com'].npmAuthToken" "${AUTH_TOKEN}"
      env:
        AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: yarn install
    - run: yarn run build
    - run: yarn run lint
    - run: yarn run test
    - run: yarn run publish
