name: run test and lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - run: npm i -g yarn
    - run: yarn install
    - run: yarn run build
    - run: yarn run lint
    - run: yarn run test
